### PR TITLE
Add varieties page sf

### PR DESCRIPTION
**Pull request by Vyryty**
Added a few directories and created rudimentary varieties page.

### CODE REVIEW

**Review by LongShotPlaya — APPROVED** [review]
Looks good

**Review by JessicaVaughan2022 — COMMENTED** [review]
looks good!

**Review by WilsonTrin — APPROVED** [review]
this is good

**Review by JessicaVaughan2022 — APPROVED** [review]

**Review by DeviFitz — APPROVED** [review]
Looks good

**Pull request merged**
