### PR TITLE
Updated background and nav bar.

### PR DESCRIPTION
**Pull request by LongShotPlaya**
I added a navigation bar. If yall like it, we should copy it to every page.

### CODE REVIEW

**Review by WilsonTrin — COMMENTED** [review]
The nav bar is a start but it definitely could use improvement imo. If we're going with a dark theme the color is better off using something like rgb 30 30 30 rather than straight black, less harsh contrast with the text. The links on the nav bar look randomly placed and immediately awkward, having them all side to side with "home" at the leftmost, "more information" at the rightmost and "resources" left of "more information" would quash that issue. I personally think it would look better if the nav bar wasn't floating and was rather attached to the sides so that you can't see the background all around it. Additionally if we want to use a background photo is should be high res probably, I can see the pixels. Text highlight color is all fine though.

**Comment by LongShotPlaya** [comment]
> I added a navigation bar. If yall like it, we should copy it to every page.

I haven't been worried about CSS yet, I've just been trying to get things working and a baseline going.

**Review by WilsonTrin — APPROVED** [review]

**Review by JessicaVaughan2022 — APPROVED** [review]
Looks good!

**Review by Vyryty — APPROVED** [review]
Looks good.

**Pull request merged**
